# Generated by Django 3.2.23 on 2024-01-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
