# Generated by Django 3.2.23 on 2024-01-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='comment',
            new_name='review',
        ),
    ]
